/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Industrial Dark/Red brand palette
        brand: {
          red:      "#C0392B",
          "red-dark":  "#96281B",
          "red-light": "#E74C3C",
          orange:   "#E67E22",
          steel:    "#2C3E50",
          "steel-light": "#34495E",
          iron:     "#F1F5F9",
          "iron-mid":  "#E2E8F0",
          "iron-light": "#CBD5E1",
          gold:     "#D4AF37",
          silver:   "#BDC3C7",
          smoke:    "#95A5A6",
        },
        background:  "#FFFFFF",
        foreground:  "#0F0F0F",
        muted:       "#F8F9FA",
        "muted-foreground": "#64748B",
        accent:      "#C0392B",
        "accent-foreground": "#FFFFFF",
        border:      "#E2E8F0",
        input:       "#FFFFFF",
        ring:        "#C0392B",
        card:        "#FFFFFF",
        "card-foreground": "#0F0F0F",
      },
      fontFamily: {
        sans:  ["var(--font-inter)", "system-ui", "sans-serif"],
        heading: ["var(--font-playfair)", "Georgia", "serif"],
        tamil: ["'Noto Sans Tamil'", "sans-serif"],
        mono:  ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        "display-2xl": ["4.5rem",  { lineHeight: "1.05", letterSpacing: "-0.02em" }],
        "display-xl":  ["3.75rem", { lineHeight: "1.08", letterSpacing: "-0.02em" }],
        "display-lg":  ["3rem",    { lineHeight: "1.1",  letterSpacing: "-0.015em" }],
        "display-md":  ["2.25rem", { lineHeight: "1.15", letterSpacing: "-0.01em" }],
        "display-sm":  ["1.875rem",{ lineHeight: "1.2"  }],
      },
      spacing: {
        "section": "7rem",
        "section-sm": "4rem",
        "18": "4.5rem",
        "88": "22rem",
        "100": "25rem",
        "128": "32rem",
      },
      backgroundImage: {
        "gradient-radial":  "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":   "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "noise": "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\")",
        "grid-pattern": "linear-gradient(rgba(192,57,43,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(192,57,43,0.03) 1px, transparent 1px)",
        "hero-gradient": "linear-gradient(135deg, #FFFFFF 0%, #FFF5F4 50%, #FFFFFF 100%)",
        "red-glow":     "radial-gradient(ellipse at center, rgba(192,57,43,0.15) 0%, transparent 70%)",
      },
      backgroundSize: {
        "grid": "60px 60px",
      },
      animation: {
        "fade-in":      "fadeIn 0.6s ease forwards",
        "slide-up":     "slideUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-in-left":"slideInLeft 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "glow-pulse":   "glowPulse 3s ease-in-out infinite",
        "shimmer":      "shimmer 2.5s linear infinite",
        "float":        "float 6s ease-in-out infinite",
        "spin-slow":    "spin 12s linear infinite",
        "marquee":      "marquee 25s linear infinite",
        "border-spin":  "borderSpin 4s linear infinite",
      },
      keyframes: {
        fadeIn:      { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp:     { from: { opacity: "0", transform: "translateY(40px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideInLeft: { from: { opacity: "0", transform: "translateX(-40px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        glowPulse:   { "0%, 100%": { opacity: "0.4" }, "50%": { opacity: "0.9" } },
        shimmer:     { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        float:       { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        marquee:     { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        borderSpin:  { "0%": { backgroundPosition: "0% 50%" }, "100%": { backgroundPosition: "200% 50%" } },
      },
      boxShadow: {
        "red-glow":   "0 0 30px rgba(192, 57, 43, 0.4)",
        "red-glow-lg":"0 0 60px rgba(192, 57, 43, 0.3), 0 0 120px rgba(192, 57, 43, 0.1)",
        "glass":      "0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255,255,255,0.05)",
        "card-hover": "0 20px 60px rgba(0,0,0,0.6), 0 0 30px rgba(192,57,43,0.15)",
        "inset-glow": "inset 0 0 30px rgba(192,57,43,0.1)",
      },
      borderRadius: {
        "xl": "1rem",
        "2xl":"1.5rem",
        "3xl":"2rem",
      },
      transitionTimingFunction: {
        "expo-out": "cubic-bezier(0.16, 1, 0.3, 1)",
        "expo-in":  "cubic-bezier(0.7, 0, 0.84, 0)",
        "back-out": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      zIndex: {
        "60":  "60",
        "70":  "70",
        "80":  "80",
        "90":  "90",
        "100": "100",
      },
    },
  },
  plugins: [],
};
